### ISSUE TITLE
License Credit

### ISSUE THREAD

**Issue by NthTensor** [LordVader9988/s#3]
This project will be a violation of the creative commons Attribution-NonCommercial-ShareAlike 4.0 International License, under which Secret Hitler and Secret-Hitler (website) are both licensed, until Chris Ozols is properly credited as the original author.

You should:
+ Provide the title, author's full name and a link to the original
+ As this is a derivative work, you must indicate changes to the original
+ Make it clear that this fork is not endorsed by or affiliated with the original author
+ Not take donations

Until this is done, Chris will have full right to revoke your license and should be able to get GitHub to remove this fork through the DMCA.

**Comment by LordVader9988** [comment]
@NthTensor are the changes I have made sufficient?
